export const fields = [
 ['surname','성','Surname','text','예. 김'],['given','이름','Given Names','text','예. 하늘'],
 ['birth','생년월일','Date of Birth','date',''],['sex','성별','Sex','select',''],
 ['place','출생지','Place of Birth','text','예. 캘거리, 에드먼턴'],['registration','등록번호','Registration No.','text','원본의 등록번호'],
 ['registered','등록일','Registration Date','date',''],['issued','발급일','Date Issued','date',''],
 ['parent1','첫 번째 부모 성명','Name of Parent · 원본 순서','text','한글 성명'],['parent1Place','첫 번째 부모 출생지','Place of Birth','text','예. 대한민국'],
 ['parent2','두 번째 부모 성명','Name of Parent · 원본 순서','text','한글 성명'],['parent2Place','두 번째 부모 출생지','Place of Birth','text','예. 대한민국']
];
export function koreanDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error('날짜를 선택해 주세요.');const [y,m,d]=value.split('-').map(Number);const date=new Date(0);date.setUTCFullYear(y,m-1,d);if(y<1000||date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d)throw new Error('유효한 날짜를 선택해 주세요.');return `${y}년 ${m}월 ${d}일`;}
export function validate(data){for(const [key,label]of fields){if(!data[key]?.trim())throw new Error(`${label} 항목을 입력해 주세요.`);}for(const key of ['registrar','registrarKo','translator'])if(!data[key]?.trim())throw new Error('등록관과 번역자 이름을 입력해 주세요.');for(const key of ['birth','registered','issued'])koreanDate(data[key]);if(!['M','F'].includes(data.sex))throw new Error('성별을 선택해 주세요.');if(data.birth>data.registered||data.registered>data.issued)throw new Error('생년월일, 등록일, 발급일의 순서를 확인해 주세요.');for(const [key]of fields.filter(f=>f[3]==='text'&&!['registration'].includes(f[0]))){if(!/[가-힣]/u.test(data[key])||/[A-Za-z]/.test(data[key]))throw new Error('성명과 출생지는 한글로 입력해 주세요.');}for(const key of ['registrarKo','translator'])if(!/[가-힣]/u.test(data[key])||/[A-Za-z]/.test(data[key]))throw new Error('등록관 한글 표기와 번역자 이름을 확인해 주세요.');if(!data.confirmed)throw new Error('등록관 이름의 한글 표기를 확인해 주세요.');for(const value of Object.values(data))if(typeof value==='string'&&value.length>100)throw new Error('입력 내용은 항목당 100자 이내로 작성해 주세요.');return data;}
const names={trevor:'트레버',bergen:'버겐',john:'존',james:'제임스',robert:'로버트',william:'윌리엄',david:'데이비드',michael:'마이클',richard:'리처드',thomas:'토머스',charles:'찰스',daniel:'대니얼',paul:'폴',mark:'마크',steven:'스티븐',stephen:'스티븐',andrew:'앤드루',peter:'피터',mary:'메리',jane:'제인',jennifer:'제니퍼',linda:'린다',susan:'수전',elizabeth:'엘리자베스',patricia:'퍼트리샤',sarah:'세라',anne:'앤',anna:'애나',margaret:'마거릿',smith:'스미스',brown:'브라운',wilson:'윌슨',johnson:'존슨',taylor:'테일러',anderson:'앤더슨',martin:'마틴',lee:'리',scott:'스콧',clark:'클라크',clarke:'클라크',roger:'로저',grove:'그로브',mohamed:'모하메드',firoz:'피로즈'};
const initials={a:'에이',b:'비',c:'시',d:'디',e:'이',f:'에프',g:'지',h:'에이치',i:'아이',j:'제이',k:'케이',l:'엘',m:'엠',n:'엔',o:'오',p:'피',q:'큐',r:'아르',s:'에스',t:'티',u:'유',v:'브이',w:'더블유',x:'엑스',y:'와이',z:'제트'};
export function suggestName(input){const parts=input.trim().split(/[\s-]+/).filter(Boolean);const missing=[];const converted=parts.map(part=>{const key=part.toLowerCase().replace(/\.$/,'');if(names[key])return names[key];if(key.length===1&&initials[key])return initials[key];missing.push(part);return '';});return {value:missing.length?'':converted.join(' '),missing};}
