export const fields = [
 ['surname','성','Surname','text','예. 김'],['given','이름','Given Names','text','예. 하늘'],
 ['birth','생년월일','Date of Birth','date',''],['sex','성별','Sex','select',''],
 ['place','출생지','Place of Birth','text','예. 캘거리, 에드먼턴'],['registration','등록번호','Registration No.','text','등록번호'],
 ['registered','등록일','Registration Date','date',''],['issued','발급일','Date Issued','date',''],
 ['parent1','모 성명','Name of Parent · 원본 순서','text','한글 성명'],['parent1Place','모 출생지','Place of Birth','text','예. 대한민국'],
 ['parent2','부 성명','Name of Parent · 원본 순서','text','한글 성명'],['parent2Place','부 출생지','Place of Birth','text','예. 대한민국']
];
export function koreanDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error('날짜를 선택해 주세요.');const [y,m,d]=value.split('-').map(Number);const date=new Date(0);date.setUTCFullYear(y,m-1,d);if(y<1000||date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d)throw new Error('유효한 날짜를 선택해 주세요.');return `${y}년 ${m}월 ${d}일`;}
export function validate(data){for(const [key,label]of fields){if(!data[key]?.trim())throw new Error(`${label} 항목을 입력해 주세요.`);}for(const key of ['registrar','registrarKo','translator'])if(!data[key]?.trim())throw new Error('등록관과 번역자 이름을 입력해 주세요.');for(const key of ['birth','registered','issued'])koreanDate(data[key]);if(!['M','F'].includes(data.sex))throw new Error('성별을 선택해 주세요.');if(data.birth>data.registered||data.registered>data.issued)throw new Error('생년월일, 등록일, 발급일의 순서를 확인해 주세요.');for(const [key]of fields.filter(f=>f[3]==='text'&&!['registration'].includes(f[0]))){if(!/[가-힣]/u.test(data[key])||/[A-Za-z]/.test(data[key]))throw new Error('성명과 출생지는 한글로 입력해 주세요.');}for(const key of ['registrarKo','translator'])if(!/[가-힣]/u.test(data[key])||/[A-Za-z]/.test(data[key]))throw new Error('등록관 한글 표기와 번역자 이름을 확인해 주세요.');if(!data.confirmed)throw new Error('등록관 이름의 한글 표기를 확인해 주세요.');for(const value of Object.values(data))if(typeof value==='string'&&value.length>100)throw new Error('입력 내용은 항목당 100자 이내로 작성해 주세요.');return data;}
const names={chris:'크리스',christopher:'크리스토퍼',christine:'크리스틴',christina:'크리스티나',kevin:'케빈',brian:'브라이언',bryan:'브라이언',ryan:'라이언',eric:'에릭',jason:'제이슨',jeffrey:'제프리',jeff:'제프',george:'조지',joseph:'조지프',patrick:'패트릭',timothy:'티머시',tim:'팀',anthony:'앤서니',donald:'도널드',douglas:'더글러스',edward:'에드워드',kenneth:'케네스',gary:'게리',larry:'래리',ronald:'로널드',alan:'앨런',allan:'앨런',adam:'애덤',alex:'알렉스',alexander:'알렉산더',benjamin:'벤저민',nicholas:'니컬러스',matthew:'매슈',nathan:'네이선',noah:'노아',oliver:'올리버',jack:'잭',jacob:'제이컵',joshua:'조슈아',henry:'헨리',luke:'루크',samuel:'새뮤얼',sam:'샘',rosemary:'로즈메리',rosemarie:'로즈마리',radke:'래드키',stephanie:'스테퍼니',emma:'에마',emily:'에밀리',olivia:'올리비아',sophia:'소피아',jessica:'제시카',julia:'줄리아',julie:'줄리',rachel:'레이철',rebecca:'리베카',laura:'로라',lisa:'리사',amy:'에이미',angela:'앤절라',helen:'헬렌',karen:'캐런',nancy:'낸시',nicole:'니콜',carol:'캐럴',catherine:'캐서린',katherine:'캐서린',michelle:'미셸',sandra:'샌드라',sharon:'섀런',victoria:'빅토리아',williams:'윌리엄스',jones:'존스',miller:'밀러',davis:'데이비스',moore:'무어',thompson:'톰프슨',white:'화이트',harris:'해리스',robinson:'로빈슨',lewis:'루이스',walker:'워커',hall:'홀',young:'영',king:'킹',wright:'라이트',hill:'힐',green:'그린',baker:'베이커',adams:'애덤스',nelson:'넬슨',carter:'카터',mitchell:'미첼',roberts:'로버츠',campbell:'캠벨',parker:'파커',evans:'에번스',edwards:'에드워즈',collins:'콜린스',stewart:'스튜어트',morris:'모리스',rogers:'로저스',reed:'리드',cook:'쿡',morgan:'모건',bell:'벨',murphy:'머피',bailey:'베일리',cooper:'쿠퍼',howard:'하워드',ward:'워드',peterson:'피터슨',gray:'그레이',trevor:'트레버',bergen:'버겐',john:'존',james:'제임스',robert:'로버트',william:'윌리엄',david:'데이비드',michael:'마이클',richard:'리처드',thomas:'토머스',charles:'찰스',daniel:'대니얼',paul:'폴',mark:'마크',steven:'스티븐',stephen:'스티븐',andrew:'앤드루',peter:'피터',mary:'메리',jane:'제인',jennifer:'제니퍼',linda:'린다',susan:'수전',elizabeth:'엘리자베스',patricia:'퍼트리샤',sarah:'세라',anne:'앤',anna:'애나',margaret:'마거릿',smith:'스미스',brown:'브라운',wilson:'윌슨',johnson:'존슨',taylor:'테일러',anderson:'앤더슨',martin:'마틴',lee:'리',scott:'스콧',clark:'클라크',clarke:'클라크',roger:'로저',grove:'그로브',mohamed:'모하메드',firoz:'피로즈'};
const initials={a:'에이',b:'비',c:'시',d:'디',e:'이',f:'에프',g:'지',h:'에이치',i:'아이',j:'제이',k:'케이',l:'엘',m:'엠',n:'엔',o:'오',p:'피',q:'큐',r:'아르',s:'에스',t:'티',u:'유',v:'브이',w:'더블유',x:'엑스',y:'와이',z:'제트'};
const koreanNames={daeyeol:'대열',kim:'김',gim:'김',ryu:'류',yoo:'유',yu:'유',lee:'이',yi:'이',park:'박',pak:'박',choi:'최',choe:'최',jung:'정',jeong:'정',cho:'조',jo:'조',kang:'강',gang:'강',ha:'하',hong:'홍',lim:'임',im:'임',yoon:'윤',yun:'윤',han:'한',oh:'오',o:'오',seo:'서',suh:'서',song:'송',shin:'신',sin:'신',jang:'장',chang:'장',kwon:'권',gwon:'권',hwang:'황',ahn:'안',an:'안',jeon:'전',moon:'문',mun:'문',son:'손',sohn:'손',bae:'배',baek:'백',nam:'남',noh:'노',ro:'노',no:'노',heo:'허',huh:'허'};
export function koreanName(input){
 const onset=['g','kk','n','d','tt','r','m','b','pp','s','ss','','j','jj','ch','k','t','p','h'];
 const vowels=['a','ae','ya','yae','eo','e','yeo','ye','o','wa','wae','oe','yo','u','wo','we','wi','yu','eu','ui','i'];
 const codas={'':0,k:1,kk:2,n:4,t:7,l:8,m:16,p:17,ng:21};
 function convert(word){if(koreanNames[word])return koreanNames[word];const memo=new Map();function solve(at){if(at===word.length)return {text:'',score:0};if(memo.has(at))return memo.get(at);let best=null;for(let i=0;i<onset.length;i++)for(let v=0;v<vowels.length;v++){const head=onset[i]+vowels[v];if(!word.startsWith(head,at))continue;for(const [tail,t]of Object.entries(codas)){const end=at+head.length+tail.length;if(!word.startsWith(tail,at+head.length))continue;const rest=solve(end);if(!rest)continue;const score=rest.score+1+(i===11&&at>0?.15:0);if(!best||score<best.score)best={text:String.fromCharCode(44032+i*588+v*28+t)+rest.text,score};}}memo.set(at,best);return best;}return solve(0)?.text||'';}
 const words=input.toLowerCase().trim().split(/\s+/);let failed=false;const result=words.map(word=>word.split('-').map(part=>{const v=convert(part);if(!v)failed=true;return v;}).join('')).join(' ');return failed?'':result;
}
export function suggestName(input,mode='english'){const parts=input.trim().split(/[\s-]+/).filter(Boolean);if(mode==='korean'){const value=koreanName(input);return{value,missing:value?[]:[input]};}const missing=[];const converted=parts.map(part=>{const key=part.toLowerCase().replace(/\.$/,'');if(names[key])return names[key];if(['daeyeol'].includes(key))return koreanNames[key];if(key.length===1&&initials[key])return initials[key];missing.push(part);return '';});return {value:missing.length?'':converted.join(' '),missing};}
export const help={surname:'출생신고할 아기의 성을 한글로 적어 주세요.',given:'성을 제외한 아기의 이름을 한글로 적어 주세요.',birth:'아기가 태어난 날짜를 선택해 주세요.',sex:'아기의 성별을 선택해 주세요.',place:'아기가 태어난 도시를 한글로 적어 주세요.',parent1:'어머니의 성과 이름을 한글로 적어 주세요.',parent1Place:'어머니가 태어난 국가·지역을 한글로 적어 주세요.',parent2:'아버지의 성과 이름을 한글로 적어 주세요.',parent2Place:'아버지가 태어난 국가·지역을 한글로 적어 주세요.'};
